import { RELATIVE_ELDERS } from "./data";

import { FindCareCaregiver, FindCareElderOption } from "@/types/find-care";

export const FIND_CARE_ELDERS: FindCareElderOption[] = RELATIVE_ELDERS.map(
  (elder) => ({
    id: elder.id,
    name: elder.name,
    relationship: elder.relationship,
    avatarLabel: elder.avatarLabel,
  }),
);

export const FIND_CARE_QUICK_FILTERS = [
  "Available Now",
  "Top Rated",
  "Nearby",
  "Medical Care",
  "Mobility Assistance",
  "Overnight Care",
];

export const FIND_CARE_CARE_TYPES = [
  "Medical Care",
  "Companionship",
  "Mobility Assistance",
  "Overnight Care",
  "Post-Surgery Care",
  "Medication Support",
];

export const FIND_CARE_LANGUAGES = [
  "English",
  "Bangla",
  "Spanish",
  "Hindi",
  "Arabic",
];

export const FIND_CARE_CAREGIVERS: FindCareCaregiver[] = [
  {
    id: "caregiver-ava-thompson",
    name: "Ava Thompson",
    avatarLabel: "AT",
    rating: 4.9,
    reviewCount: 128,
    hourlyRate: 28,
    experienceYears: 6,
    specializations: ["Medical Care", "Medication Support", "Mobility"],
    distanceMiles: 1.2,
    etaMinutes: 12,
    languages: ["English", "Spanish"],
    availability: "available-now",
    isHighlyRated: true,
    isNearby: true,
    bio: "Registered caregiver with a calm bedside manner and a strong focus on medication routines, recovery support, and wellness checks.",
    certifications: ["CPR", "First Aid", "Home Health Aide"],
    completedSessions: 412,
    serviceRadiusMiles: 8,
    coordinate: { latitude: 40.742, longitude: -73.991 },
    availabilityWindow: "Today, 8:00 AM - 8:00 PM",
    careTypes: ["Medical Care", "Mobility Assistance", "Medication Support"],
    routeLabel: "12 min arrival",
    reviews: [
      {
        id: "review-ava-1",
        author: "Elena Rodriguez",
        rating: 5,
        comment: "Very attentive, calm, and clear during medication support.",
        timestamp: "2 weeks ago",
      },
      {
        id: "review-ava-2",
        author: "Family member",
        rating: 4.9,
        comment:
          "Kept us updated throughout the session with reassuring detail.",
        timestamp: "1 month ago",
      },
    ],
  },
  {
    id: "caregiver-priya-nair",
    name: "Priya Nair",
    avatarLabel: "PN",
    rating: 4.8,
    reviewCount: 97,
    hourlyRate: 24,
    experienceYears: 5,
    specializations: ["Companionship", "Overnight Care", "Wellness"],
    distanceMiles: 1.8,
    etaMinutes: 16,
    languages: ["English", "Hindi"],
    availability: "scheduled",
    isHighlyRated: true,
    isNearby: true,
    bio: "Friendly caregiver known for structured routines, companionship, and smooth handoffs for evening and overnight support.",
    certifications: ["CPR", "Dementia Care"],
    completedSessions: 278,
    serviceRadiusMiles: 10,
    coordinate: { latitude: 40.746, longitude: -73.982 },
    availabilityWindow: "Today, 4:00 PM - 11:00 PM",
    careTypes: ["Companionship", "Overnight Care", "Medical Care"],
    routeLabel: "16 min arrival",
    reviews: [
      {
        id: "review-priya-1",
        author: "Arthur Pendelton",
        rating: 4.8,
        comment: "Really thoughtful and proactive with check-ins and comfort.",
        timestamp: "6 days ago",
      },
    ],
  },
  {
    id: "caregiver-nora-williams",
    name: "Nora Williams",
    avatarLabel: "NW",
    rating: 4.7,
    reviewCount: 84,
    hourlyRate: 22,
    experienceYears: 4,
    specializations: ["Mobility Assistance", "Post-Surgery Care"],
    distanceMiles: 2.3,
    etaMinutes: 19,
    languages: ["English"],
    availability: "available-now",
    isHighlyRated: false,
    isNearby: true,
    bio: "Hands-on caregiver who supports mobility, transfers, and rehab routines with a safety-first approach.",
    certifications: ["Transfer Safety", "CPR"],
    completedSessions: 215,
    serviceRadiusMiles: 7,
    coordinate: { latitude: 40.7395, longitude: -73.998 },
    availabilityWindow: "Tonight, 6:00 PM - 10:00 PM",
    careTypes: ["Mobility Assistance", "Post-Surgery Care"],
    routeLabel: "19 min arrival",
    reviews: [
      {
        id: "review-nora-1",
        author: "Maria Chen",
        rating: 4.7,
        comment:
          "Patient, reassuring, and especially good with transfer support.",
        timestamp: "3 days ago",
      },
    ],
  },
  {
    id: "caregiver-samira-ahmed",
    name: "Samira Ahmed",
    avatarLabel: "SA",
    rating: 4.9,
    reviewCount: 141,
    hourlyRate: 30,
    experienceYears: 8,
    specializations: ["Medical Care", "Overnight Care", "Medication"],
    distanceMiles: 3.1,
    etaMinutes: 24,
    languages: ["English", "Bangla", "Arabic"],
    availability: "available-now",
    isHighlyRated: true,
    isNearby: false,
    bio: "Premium care specialist with a hospital background and strong experience in overnight medical support.",
    certifications: ["RN Assistant", "CPR", "Clinical Support"],
    completedSessions: 531,
    serviceRadiusMiles: 12,
    coordinate: { latitude: 40.751, longitude: -73.977 },
    availabilityWindow: "Today, 10:00 AM - 9:00 PM",
    careTypes: ["Medical Care", "Overnight Care", "Medication Support"],
    routeLabel: "24 min arrival",
    reviews: [
      {
        id: "review-samira-1",
        author: "Relative",
        rating: 5,
        comment:
          "Very professional, efficient, and clear on all health updates.",
        timestamp: "1 week ago",
      },
    ],
  },
  {
    id: "caregiver-michael-owens",
    name: "Michael Owens",
    avatarLabel: "MO",
    rating: 4.6,
    reviewCount: 62,
    hourlyRate: 20,
    experienceYears: 3,
    specializations: ["Companionship", "Light Support"],
    distanceMiles: 4.4,
    etaMinutes: 29,
    languages: ["English", "French"],
    availability: "offline",
    isHighlyRated: false,
    isNearby: false,
    bio: "Warm and reliable caregiver ideal for companionship, check-ins, and lighter support schedules.",
    certifications: ["Companion Care"],
    completedSessions: 108,
    serviceRadiusMiles: 6,
    coordinate: { latitude: 40.735, longitude: -73.969 },
    availabilityWindow: "Tomorrow, 9:00 AM - 5:00 PM",
    careTypes: ["Companionship", "Medical Care"],
    routeLabel: "29 min arrival",
    reviews: [
      {
        id: "review-michael-1",
        author: "Family member",
        rating: 4.6,
        comment: "Excellent companion care and very easy to coordinate with.",
        timestamp: "2 weeks ago",
      },
    ],
  },
];

export const FIND_CARE_DEFAULT_REGION = {
  latitude: 40.744,
  longitude: -73.985,
  latitudeDelta: 0.045,
  longitudeDelta: 0.045,
};
